// 日本テーマのカテゴリーとプロンプト集
// モックモード時はmockImagesからランダムに画像を選ぶ
// 本番モード時はpromptsをAIに渡して画像を生成する

const categories = [
  {
    name: 'Edo',
    nameJa: '江戸',
    kanji: '江',
    gradient: 'from-amber-950 to-yellow-900',
    type: 'image',
    price: 190,
    tags: ['9:16', 'historical', 'edo', 'japan'],
    resolution: '576 × 1024 (9:16)',
    format: 'JPEG / PNG',
    fileSize: '~8MB',
    usecases: ['AI Narration', 'History', 'YouTube Shorts'],
    sceneTemplates: [
      'A quiet Edo street at dusk — perfect for AI narration on tradition and craftsmanship.',
      'Merchants and lanterns of old Japan — ideal background for history or culture content.',
      'The stillness of Edo-era life — sets the tone for reflective AI voiceover videos.',
    ],
    prompts: [
      'Edo period Nihonbashi merchant district at dusk, traditional wooden two-story machiya townhouses with noren curtains, stone-paved road, paper lanterns glowing amber, townsfolk in cotton kimono, no readable text, cinematic vertical composition',
      'Edo era Sumida river at twilight, wooden merchant barges moored along stone embankment, weeping willows trailing in water, stone lanterns reflecting on still surface, no signs, painterly vertical light',
      'Traditional Edo bathhouse (sento) exterior at night, warm orange light spilling from noren doorway, wooden architecture, steam wisps rising, cobblestone alley, no text',
      'Edo period Asakusa temple approach (nakamise) at dawn before crowds, wooden stall shutters closed, stone lanterns lit, five-story pagoda visible through morning mist, no text',
      'Ancient Edo castle Otemon gate at sunrise, massive stone ishigaki foundation, pine trees silhouette, mist over the moat, majestic and serene, no text',
      'Traditional Japanese teahouse (chashitsu) in Edo era roji garden, stepping stones, bamboo fence, tatami visible through open shoji, soft morning light, no text',
      'Edo period sumo training stable (heya) exterior, wrestlers in silhouette practicing in courtyard, wooden architecture, early morning mist, no text',
    ],
    mockImages: [
      'https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=800&q=80',
      'https://images.unsplash.com/photo-1478436127897-769e1b3f0f36?w=800&q=80',
      'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=800&q=80',
    ],
    titleTemplates: [
      'Nihonbashi at Dusk',
      'Sumida River Twilight',
      'Edo Bathhouse Night',
      'Asakusa Before Dawn',
      'Castle Gate at Sunrise',
      'Chashitsu Morning',
    ],
  },
  {
    name: 'Kyoto',
    nameJa: '京都',
    kanji: '京',
    gradient: 'from-red-950 to-pink-900',
    type: 'image',
    price: 190,
    tags: ['9:16', 'kyoto', 'temple', 'traditional'],
    resolution: '576 × 1024 (9:16)',
    format: 'JPEG / PNG',
    fileSize: '~8MB',
    usecases: ['AI Narration', 'Meditation', 'YouTube Shorts'],
    sceneTemplates: [
      'Ancient Kyoto in silence — perfect backdrop for mindfulness or cultural AI narration.',
      'The timeless beauty of temples and torii — ideal for meditative or travel content.',
      'Kyoto at its most serene — sets the mood for reflective voiceover videos.',
    ],
    prompts: [
      'Fushimi Inari shrine at dawn, thousands of vermilion torii gates receding into misty cedar forest, stone fox statues, no people, vertical composition, no text',
      'Arashiyama bamboo grove, towering green stalks forming cathedral-like vertical canopy, dappled sunlight, narrow path, peaceful and meditative, no text',
      'Kinkaku-ji golden pavilion reflected in mirror-still Kyoko-chi pond, autumn maple trees in vivid red and gold, vertical composition, no text',
      'Pontocho alley Kyoto at night, narrow cobblestone lane between traditional machiya, red paper lanterns glowing warm, wet stone reflecting orange light, no readable signs',
      'Maiko in elaborate Kyo-katsura wig and furisode kimono walking through Gion stone-paved lane, autumn maple leaves falling, cinematic, no text',
      'Philosopher\'s Path Kyoto in spring, narrow canal lined with sakura in full bloom, stone path, wooden fences, peaceful vertical perspective, no text',
      'Ryoan-ji zen temple raked karesansui gravel garden, fifteen stones in composition, moss borders, ancient clay wall, golden morning light, no text',
    ],
    mockImages: [
      'https://images.unsplash.com/photo-1478436127897-769e1b3f0f36?w=800&q=80',
      'https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=800&q=80',
      'https://images.unsplash.com/photo-1522383225653-ed111181a951?w=800&q=80',
    ],
    titleTemplates: [
      'Fushimi Inari at Dawn',
      'Bamboo Grove Silence',
      'Golden Temple Reflection',
      'Pontocho Night',
      'Philosopher\'s Path Spring',
      'Ryoan-ji Morning',
    ],
  },
  {
    name: 'Samurai',
    nameJa: '侍',
    kanji: '侍',
    gradient: 'from-slate-900 to-gray-800',
    type: 'image',
    price: 390,
    tags: ['9:16', 'samurai', 'warrior', 'historical', 'authentic'],
    resolution: '576 × 1024 (9:16)',
    format: 'JPEG / PNG',
    fileSize: '~8MB',
    usecases: ['AI Narration', 'History', 'TikTok'],
    sceneTemplates: [
      'A warrior at peace, blade set aside — perfect for AI narration on discipline and inner strength.',
      'Honor, silence, and steel — ideal visual for motivational or historical AI video content.',
      'The lone samurai at the edge of battle — sets the scene for legacy and courage narratives.',
    ],
    prompts: [
      'Edo period samurai retainer in black-lacquered tosei-gusoku full armor, kabuto helmet with kuwagata horns and shikoro neck guard, daisho katana-wakizashi pair thrust at left hip edge upward, cherry blossom castle courtyard, no text, historically accurate Japanese armor',
      'Lone ronin in worn gray hemp kimono and dark hakama, single katana at left hip edge facing upward, chonmage topknot hairstyle with shaved pate, standing at foggy crossroads at dawn, no text, authentic Edo period warrior',
      'Samurai in red-laced do-maru chest armor kneeling in prayer before a Shinto torii gate, kabuto helmet placed respectfully beside him, incense smoke curling upward, dramatic vertical shaft of light, no text',
      'Edo period samurai in formal haori jacket bearing family kamon crest over dark hakama, daisho at left hip, seated in tatami room with shoji screens casting geometric shadows, no text',
      'Close-up of authentic tosei-gusoku Japanese armor: black-lacquered okegawa-do chest piece with dark blue silk odoshi lacing, family kamon on sendan-no-ita shoulder guard, dramatic studio lighting, no text',
      'Ronin silhouette against winter sunset at snow-covered wooden bridge, single katana on left hip, chonmage visible in profile, fog rising from river below, cinematic vertical composition, no text',
      'Samurai general astride black horse, sashimono back banner with Japanese kamon crest, full tosei-gusoku armor, autumn maple forest, historically accurate, no text',
    ],
    mockImages: [
      'https://images.unsplash.com/photo-1542051841857-5f90071e7989?w=800&q=80',
      'https://images.unsplash.com/photo-1478436127897-769e1b3f0f36?w=800&q=80',
      'https://images.unsplash.com/photo-1508184964240-ee96bb9677a7?w=800&q=80',
    ],
    titleTemplates: [
      'The Last Ronin',
      'Warrior at the Gate',
      'Armor of the Edo Clan',
      'Winter Vigil',
      'Kneeling Before the Shrine',
      'The General\'s Campaign',
    ],
  },
  {
    name: 'Bakumatsu',
    nameJa: '幕末',
    kanji: '幕',
    gradient: 'from-zinc-900 to-stone-800',
    type: 'image',
    price: 390,
    tags: ['9:16', 'bakumatsu', 'samurai', 'historical', 'authentic'],
    resolution: '576 × 1024 (9:16)',
    format: 'JPEG / PNG',
    fileSize: '~8MB',
    usecases: ['AI Narration', 'History', 'YouTube Shorts'],
    sceneTemplates: [
      'Japan at the edge of transformation — perfect for AI narration on change and sacrifice.',
      'The last age of the samurai — ideal visual for historical or legacy-themed content.',
      'Honor meeting modernity — sets the tone for narratives about courage and inevitability.',
    ],
    prompts: [
      'Bakumatsu era shishi loyalist in dark indigo kimono and black hakama, single katana at left hip edge upward, rain-soaked Pontocho narrow alley at night, red paper lanterns reflecting in puddles, no text, 1860s Japan',
      'Shinsengumi warrior in distinctive pale blue haori with white mountain-stripe crest on shoulders, katana drawn in chudan-no-kamae defensive stance, moonlit Kyoto street beside traditional machiya, no text, historically accurate uniform',
      'Bakumatsu era scene at Hakodate harbor at dusk, lone samurai in hakama watching Western black-hulled steam warships anchored in bay, clash of old and new Japan, dramatic vertical composition, no text',
      'Battle-weary samurai in worn battle-damaged tosei-gusoku armor standing amid autumn maple forest, contemplative expression, shafts of golden light through red leaves, end of an era atmosphere, no text',
      'Meiji Restoration era loyalist in hakama and tabi sandals with Western-style wool overcoat draped over shoulders, single katana, standing before Nijo Castle gate at dawn, symbolic of Japan\'s transformation, no text',
      'Group of Shinsengumi in pale blue haori coats patrolling moonlit Gion district stone path, traditional machiya buildings, wet cobblestones, tense atmosphere, historically accurate, no text',
      'Dramatic bakumatsu duel at dawn on wooden bridge over misty river, two figures in kimono-hakama in iai sword drawing stance, moment before clash, cinematic vertical composition, no text',
    ],
    mockImages: [
      'https://images.unsplash.com/photo-1542051841857-5f90071e7989?w=800&q=80',
      'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=800&q=80',
      'https://images.unsplash.com/photo-1508184964240-ee96bb9677a7?w=800&q=80',
    ],
    titleTemplates: [
      'Shinsengumi Night Patrol',
      'The Last Shishi',
      'Harbor of Black Ships',
      'Dawn of a New Era',
      'Pontocho Rain Duel',
      'The Fallen Bakufu',
    ],
  },
  {
    name: 'Sengoku',
    nameJa: '戦国',
    kanji: '戦',
    gradient: 'from-red-950 to-stone-900',
    type: 'image',
    price: 390,
    tags: ['9:16', 'sengoku', 'samurai', 'battle', 'historical', 'authentic'],
    resolution: '576 × 1024 (9:16)',
    format: 'JPEG / PNG',
    fileSize: '~8MB',
    usecases: ['AI Narration', 'History', 'TikTok'],
    sceneTemplates: [
      'Warlords and battlefield fog — perfect for AI narration on ambition and legacy.',
      'The age of warring states, frozen in time — ideal for epic historical content.',
      'Armies clash at dawn — sets the stage for strategy or leadership themed videos.',
    ],
    prompts: [
      'Sengoku period samurai warlord in elaborate golden kabuto helmet with towering standing crest, full tosei-gusoku battle armor, commanding hilltop position, colorful nobori battle flags with Japanese kamon crests in background, no text',
      'Ashigaru foot soldiers in simple okegawa-do cuirass and jingasa conical helmets marching in formation through misty dawn, yari spears raised at uniform angle, no text, historically accurate Sengoku equipment',
      'Sengoku era castle siege at night, fire arrows arcing across dark sky, stone ishigaki castle walls lit orange from below, armored defenders in silhouette, dramatic vertical composition, no text',
      'Single combat between two Sengoku samurai generals on misty riverbank, both in full tosei-gusoku armor with kabuto, katana clashing, water splashing, epic cinematic moment, no text',
      'Aftermath of Sengoku battle, lone samurai in battle-worn do-maru armor standing among fallen nobori flags on foggy field, haunting and solemn atmosphere, no text',
      'Himeji-style white plaster castle tower (tenshu) rising above stone ishigaki foundation, surrounded by cherry blossoms in full bloom, early morning mist, period-accurate Sengoku architecture, no text',
      'Sengoku arquebusiers (teppo-shu) kneeling in firing line formation, matchlock tanegashima guns, bamboo spear phalanx of ashigaru visible behind, historic battlefield formation, dramatic lighting, no text',
    ],
    mockImages: [
      'https://images.unsplash.com/photo-1542051841857-5f90071e7989?w=800&q=80',
      'https://images.unsplash.com/photo-1478436127897-769e1b3f0f36?w=800&q=80',
      'https://images.unsplash.com/photo-1508184964240-ee96bb9677a7?w=800&q=80',
    ],
    titleTemplates: [
      'The Warlord\'s Stand',
      'March of the Ashigaru',
      'Castle Under Fire',
      'Generals\' Duel',
      'Field of Fallen Banners',
      'White Castle in Bloom',
    ],
  },
  {
    name: 'Fuji',
    nameJa: '富士',
    kanji: '富',
    gradient: 'from-blue-900 to-indigo-800',
    type: 'image',
    price: 190,
    tags: ['9:16', 'fuji', 'mountain', 'landscape'],
    resolution: '576 × 1024 (9:16)',
    format: 'JPEG / PNG',
    fileSize: '~8MB',
    usecases: ['AI Narration', 'Meditation', 'Lofi Background'],
    sceneTemplates: [
      'Mount Fuji in eternal stillness — perfect background for lofi, meditation, or mindfulness content.',
      'Japan\'s sacred peak above the clouds — ideal for AI narration on perseverance and awe.',
      'The iconic silhouette of Fuji — sets a calming, cinematic tone for any voiceover video.',
    ],
    prompts: [
      'Mount Fuji at golden hour seen from below, perfect snow-capped cone rising above cherry blossom foreground, Lake Kawaguchi reflection, vertical composition, no text',
      'Mount Fuji in winter at dawn, snow-capped peak emerging from sea of clouds, dramatic crimson sky, traditional five-story pagoda silhouette in foreground, no text',
      'Mount Fuji at night, Milky Way galaxy arcing above the volcanic peak, star trails in circular motion, long exposure, no text',
      'Mount Fuji seen through tall vermilion torii gate of Fuji Sengen shrine, morning mist, cedar forest framing, spiritual vertical composition, no text',
      'Sunrise over Mount Fuji from high altitude, sea of clouds far below, sky transitioning orange to purple, climbers\' silhouettes on path, no text',
      'Mount Fuji in autumn rain, dark moody atmosphere, low clouds wrapping mid-slope, old wooden fishing boats on Lake Yamanaka, vertical composition, no text',
      'Mount Fuji reflected perfectly in flooded rice paddy field at dawn, farmer silhouette with yoke in foreground, rural Japan landscape, no text',
    ],
    mockImages: [
      'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800&q=80',
      'https://images.unsplash.com/photo-1508184964240-ee96bb9677a7?w=800&q=80',
      'https://images.unsplash.com/photo-1522383225653-ed111181a951?w=800&q=80',
    ],
    titleTemplates: [
      'Fuji at Golden Hour',
      'Sacred Peak in Winter',
      'Fuji Star Trails',
      'Through the Torii',
      'Above the Clouds',
      'Fuji in the Rice Fields',
    ],
  },
  {
    name: 'Ukiyo-e',
    nameJa: '浮世絵',
    kanji: '浮',
    gradient: 'from-teal-900 to-emerald-800',
    type: 'image',
    price: 290,
    tags: ['9:16', 'ukiyo-e', 'art', 'woodblock'],
    resolution: '576 × 1024 (9:16)',
    format: 'JPEG / PNG',
    fileSize: '~8MB',
    usecases: ['AI Narration', 'Art', 'YouTube Shorts'],
    sceneTemplates: [
      'Centuries of Japanese art distilled in one frame — perfect for cultural or artistic AI content.',
      'Woodblock mastery reimagined for the vertical screen — ideal for art history narration.',
      'The floating world of Edo, alive again — sets an artistic tone for any creator\'s story.',
    ],
    prompts: [
      'Hokusai Great Wave off Kanagawa reimagined in vertical portrait format, towering wave framing snow-capped Fuji, Prussian blue palette, bold flat graphic style, woodblock print aesthetic, no text',
      'Ukiyo-e style bijin-ga portrait, elegant woman in elaborate kanzashi hair ornaments and layered furisode kimono, cherry blossom background, vivid Edo-palette colors, flat graphic style, no text',
      'Hiroshige-style rain scene on Ohashi bridge, heavy vertical rain lines, silhouetted figures with bamboo umbrellas crossing wooden bridge, indigo and sepia palette, no text',
      'Japanese woodblock print of ryu dragon ascending through storm clouds, bold red and gold scales, crashing waves below, traditional Edo illustration style, no text',
      'Ukiyo-e style Mount Fuji with travelers on Tokaido road path, stylized flat clouds, pine trees framing, classic Hokusai composition, vivid vermilion and indigo, no text',
      'Traditional Japanese woodblock print of autumn deer in crimson maple forest, warm russet and gold tones, ink-wash background, elegant and refined, no text',
      'Ukiyo-e crane and wave composition, white crane with red crown flying over crashing ocean waves, bold indigo and white palette, gold accents, no text',
    ],
    mockImages: [
      'https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=800&q=80',
      'https://images.unsplash.com/photo-1522383225653-ed111181a951?w=800&q=80',
      'https://images.unsplash.com/photo-1478436127897-769e1b3f0f36?w=800&q=80',
    ],
    titleTemplates: [
      'The Great Wave Reborn',
      'Bijin-ga in Bloom',
      'Rain on Ohashi Bridge',
      'Dragon Ascending',
      'Tokaido Travelers',
      'Cranes Over the Sea',
    ],
  },
  {
    name: 'Night',
    nameJa: '夜景',
    kanji: '夜',
    gradient: 'from-violet-950 to-purple-900',
    type: 'image',
    price: 190,
    tags: ['9:16', 'night', 'neon', 'atmospheric'],
    resolution: '576 × 1024 (9:16)',
    format: 'JPEG / PNG',
    fileSize: '~8MB',
    usecases: ['Lofi Background', 'TikTok', 'AI Narration'],
    sceneTemplates: [
      'Tokyo after dark, lanterns glowing — perfect backdrop for lofi or city ambiance content.',
      'Neon reflections on wet streets — ideal for atmospheric or urban storytelling videos.',
      'The quiet pulse of Japan at night — sets a moody, cinematic tone for any creator.',
    ],
    prompts: [
      'Tokyo narrow izakaya alley at night, red and orange paper lanterns strung overhead, rain reflections on wet cobblestones, bokeh lights, warm intimate atmosphere, no legible text, vertical composition',
      'Osaka Dotonbori canal at night, colorful neon reflections shimmering on dark water below bridges, vertical perspective looking down narrow canal, no readable signs',
      'Tokyo rooftop terrace at night, Tokyo Tower glowing red and white in distance, vast bokeh city lights spreading to horizon, moody atmospheric vertical shot, no text',
      'Traditional Japanese ryokan at night, glowing paper andon lanterns lining engawa veranda, koi pond reflecting starlight and lantern light, serene garden darkness, no text',
      'Kyoto lantern festival at night, hundreds of washi paper lanterns floating on dark river, temples silhouetted behind, magical vertical reflection in water, no text',
      'Japanese summer matsuri festival at night, wooden yatai food stalls with warm golden noren curtains, silhouetted crowd in yukata, no signs visible, festive vertical scene',
      'Shinkansen bullet train at night station platform, blue-white LED platform lighting, sleek white train nose reflecting lights, motion blur departure, no text',
    ],
    mockImages: [
      'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800&q=80',
      'https://images.unsplash.com/photo-1542051841857-5f90071e7989?w=800&q=80',
      'https://images.unsplash.com/photo-1508184964240-ee96bb9677a7?w=800&q=80',
    ],
    titleTemplates: [
      'Izakaya Alley at Midnight',
      'Dotonbori Neon Canal',
      'Tokyo Tower Night View',
      'Lantern Inn Reflection',
      'River of Lanterns',
      'Summer Festival Glow',
    ],
  },
  {
    name: 'Shibuya',
    nameJa: '渋谷',
    kanji: '渋',
    gradient: 'from-pink-900 to-rose-800',
    type: 'image',
    price: 190,
    tags: ['9:16', 'shibuya', 'modern', 'tokyo'],
    resolution: '576 × 1024 (9:16)',
    format: 'JPEG / PNG',
    fileSize: '~8MB',
    usecases: ['TikTok', 'AI Narration', 'YouTube Shorts'],
    sceneTemplates: [
      'The organized chaos of Shibuya crossing — perfect for modern Japan or lifestyle AI content.',
      'Neon Tokyo from street level — ideal visual for travel, fashion, or culture videos.',
      'Urban Japan at its most electric — sets a dynamic backdrop for any short-form creator.',
    ],
    prompts: [
      'Shibuya crossing at night from street level looking up, hundreds of pedestrians, neon signs reflecting on wet pavement above, rain bokeh, cinematic vertical composition, no readable text',
      'Harajuku Takeshita Street in golden hour, colorful youth fashion, vertical perspective down narrow pedestrian street lined with small boutiques, no readable signs',
      'Shibuya rooftop observation deck at night, Tokyo cityscape spreading in all directions, Skytree glowing on horizon, dramatic vertical composition looking up into starless city sky, no text',
      'Tokyo Shinjuku skyscraper corridor at twilight, glass towers with glowing windows rising symmetrically on both sides, dramatic vertical vanishing point, cinematic, no text',
      'Akihabara Electric Town at night, glowing LEDs and anime screen displays, futuristic urban canyon, vertical neon corridor, no legible text, atmospheric',
      'Odaiba waterfront promenade at night, Rainbow Bridge illuminated in color, reflections on Tokyo Bay below, Ferris wheel glowing, vertical composition, no text',
      'Tokyo underground subway entrance at night, illuminated steps descending into warm orange glow, rain on pavement above, urban loneliness, cinematic, no text',
    ],
    mockImages: [
      'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800&q=80',
      'https://images.unsplash.com/photo-1542051841857-5f90071e7989?w=800&q=80',
      'https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=800&q=80',
    ],
    titleTemplates: [
      'Shibuya Crossing Rain',
      'Harajuku Golden Hour',
      'Shibuya Sky View',
      'Shinjuku Canyon',
      'Akihabara Neon Night',
      'Odaiba Rainbow Night',
    ],
  },
  {
    name: 'Shrine',
    nameJa: '神社',
    kanji: '神',
    gradient: 'from-orange-900 to-red-800',
    type: 'image',
    price: 190,
    tags: ['9:16', 'shrine', 'spiritual', 'traditional'],
    resolution: '576 × 1024 (9:16)',
    format: 'JPEG / PNG',
    fileSize: '~8MB',
    usecases: ['Meditation', 'AI Narration', 'Lofi Background'],
    sceneTemplates: [
      'Sacred torii and cedar shadows — perfect backdrop for spiritual or mindfulness AI content.',
      'Where Japan meets the divine — ideal for meditation, zen, or cultural narration videos.',
      'Ancient shrine in morning mist — sets a deeply peaceful tone for reflective creators.',
    ],
    prompts: [
      'Ancient Shinto shrine pathway deep in cedar forest, moss-covered stone komainu guardian dogs flanking steps, stone torii gate wrapped in shimenawa rope, sacred mist, vertical composition, no text',
      'Traditional Japanese matsuri portable shrine (mikoshi) procession, gilded phoenix on top, bearers in white happi coats, crowd lining the street, festive atmosphere, no text',
      'Meiji Jingu shrine inner garden approach, enormous cedar torii gate, gravel path between towering ancient trees, solitary priest in white and purple robes, no text',
      'Japanese shrine at sakura season, vermilion torii gates framed by clouds of pink cherry blossoms, stone path with fallen petals, vertical composition, spiritual beauty, no text',
      'Itsukushima shrine floating torii gate at high tide, vermilion pillars rising from calm sea, golden sunset behind Mount Misen, iconic Japan, vertical composition, no text',
      'Mountain shrine at peak autumn koyo, blazing crimson and orange maple leaves surrounding ancient stone steps, misty valley below, lone pilgrim ascending, no text',
      'Lantern-lined shrine pathway at night, hundreds of stone toro lanterns glowing amber in sequence, cedar forest darkness on either side, dramatic vertical perspective, no text',
    ],
    mockImages: [
      'https://images.unsplash.com/photo-1478436127897-769e1b3f0f36?w=800&q=80',
      'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=800&q=80',
      'https://images.unsplash.com/photo-1522383225653-ed111181a951?w=800&q=80',
    ],
    titleTemplates: [
      'Sacred Forest Gate',
      'Mikoshi Festival',
      'Meiji Shrine Dawn',
      'Blossom Shrine Path',
      'Floating Torii at Sunset',
      'Autumn Pilgrimage',
    ],
  },
  {
    name: 'Nature',
    nameJa: '自然',
    kanji: '然',
    gradient: 'from-green-900 to-teal-800',
    type: 'image',
    price: 190,
    tags: ['9:16', 'nature', 'landscape', 'japan'],
    resolution: '576 × 1024 (9:16)',
    format: 'JPEG / PNG',
    fileSize: '~8MB',
    usecases: ['Meditation', 'Lofi Background', 'AI Narration'],
    sceneTemplates: [
      'Japan\'s untouched wilderness in one vertical frame — perfect for relaxation or nature content.',
      'Seasons, silence, and natural beauty — ideal background for lofi or mindfulness videos.',
      'The raw soul of the Japanese landscape — sets a serene, immersive tone for any creator.',
    ],
    prompts: [
      'Japanese outdoor rotenburo onsen hot spring at dawn, steam rising from dark mineral water, autumn forest in full red and gold koyo surrounding stone bath, serene mountain valley, no text',
      'Nikko Kegon waterfall plunging 97 meters into gorge below, lush green summer forest framing the cascade, mist rising, dramatic vertical composition, no text',
      'Japanese terraced rice paddy fields (tanada) on hillside in summer, perfect green terraces stepping down mountainside, traditional farmhouse (minka) in valley, golden afternoon light, no text',
      'Okinawa Kerama island coastline, crystal turquoise water over white coral sand, vertical aerial perspective, tropical paradise, no text',
      'Hokkaido Furano lavender fields in summer, rolling purple and green striped hills extending to horizon, blue sky with white cumulus clouds, wide vertical composition, no text',
      'Japanese maple (momiji) garden at peak autumn, vivid vermilion and scarlet canopy over mossy stone path, zen garden stream, dappled light, no text',
      'Japanese macaque snow monkey family bathing in steaming onsen, detailed close-up, winter steam and frost on surrounding rocks and trees, Nagano atmosphere, no text',
    ],
    mockImages: [
      'https://images.unsplash.com/photo-1508184964240-ee96bb9677a7?w=800&q=80',
      'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800&q=80',
      'https://images.unsplash.com/photo-1522383225653-ed111181a951?w=800&q=80',
    ],
    titleTemplates: [
      'Mountain Rotenburo Dawn',
      'Kegon Falls',
      'Tanada Golden Light',
      'Kerama Turquoise',
      'Furano Lavender',
      'Momiji Garden',
    ],
  },
]

module.exports = categories
