// 日本テーマのカテゴリーとプロンプト集
// モックモード時はmockImagesからランダムに画像を選ぶ
// 本番モード時はpromptsをAIに渡して画像を生成する

const categories = [
  {
    name: 'Edo',
    nameJa: '江戸',
    kanji: '江',
    gradient: 'from-amber-950 to-yellow-900',
    type: 'image',
    price: 190,
    tags: ['4K', 'historical', 'edo', 'japan'],
    resolution: '576 × 1024 (9:16)',
    format: 'JPEG / PNG',
    fileSize: '~8MB',
    prompts: [
      'Edo period castle town at dusk, traditional wooden buildings with paper lanterns glowing, merchants in kimono, no readable text, cinematic atmosphere',
      'Edo era riverside at twilight, wooden merchant boats moored along a calm canal, weeping willows, stone lanterns, no signs, painterly light',
      'Samurai warrior in full armor standing in an Edo period castle courtyard, cherry blossoms falling, cinematic composition, no text',
      'Traditional Japanese bathhouse in Edo period, steam rising gently, wooden architecture, atmospheric mist, warm golden light, no text',
      'Edo period canal at dusk, merchant boats, weeping willows, stone lanterns reflecting in still water, no signs or text',
      'Ancient Edo castle gates at sunrise, mist over the moat, pine trees silhouettes, majestic and serene, no text',
      'Traditional Japanese teahouse in Edo era garden, tatami visible through open shoji, bamboo fence, soft morning light, no text',
      'Edo period sumo match inside a traditional wooden arena, crowd in silhouette, dramatic spotlighting, no signs or text',
    ],
    mockImages: [
      'https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=800&q=80',
      'https://images.unsplash.com/photo-1478436127897-769e1b3f0f36?w=800&q=80',
      'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=800&q=80',
    ],
    titleTemplates: [
      'Edo Market at Dusk',
      'Samurai\'s Path',
      'Castle Gate at Dawn',
      'Old Tokyo Canal',
      'Merchant Quarter',
      'Edo Teahouse Garden',
    ],
  },
  {
    name: 'Kyoto',
    nameJa: '京都',
    kanji: '京',
    gradient: 'from-red-950 to-pink-900',
    type: 'image',
    price: 190,
    tags: ['4K', 'kyoto', 'temple', 'traditional'],
    resolution: '576 × 1024 (9:16)',
    format: 'JPEG / PNG',
    fileSize: '~8MB',
    prompts: [
      'Fushimi Inari shrine at dawn, thousands of vermilion torii gates, morning mist, no people, ethereal atmosphere',
      'Arashiyama bamboo grove in Kyoto, towering green stalks, dappled sunlight, peaceful and meditative',
      'Kinkaku-ji golden pavilion reflected in mirror-still pond, autumn maple trees, warm afternoon light',
      'Gion district Kyoto at night, traditional machiya townhouses, paper lanterns glowing warm, cobblestone streets wet with rain, no signs or text',
      'Geisha in elaborate kimono walking through Kyoto autumn garden, maple leaves falling around her, cinematic, no text',
      'Philosopher\'s Path Kyoto in spring, narrow canal lined with cherry blossoms in full bloom, stone path, no text',
      'Kyoto traditional market alley, colorful fabric banners and food displays, atmospheric light, no legible text or signs',
      'Kyoto zen temple raked gravel garden, moss and stones, minimalist composition, morning light',
    ],
    mockImages: [
      'https://images.unsplash.com/photo-1478436127897-769e1b3f0f36?w=800&q=80',
      'https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=800&q=80',
      'https://images.unsplash.com/photo-1522383225653-ed111181a951?w=800&q=80',
    ],
    titleTemplates: [
      'Fushimi Inari at Dawn',
      'Bamboo Grove Silence',
      'Golden Temple Reflection',
      'Gion Night Walk',
      'Philosopher\'s Path Spring',
      'Zen Garden Morning',
    ],
  },
  {
    name: 'Samurai',
    nameJa: '侍',
    kanji: '侍',
    gradient: 'from-slate-900 to-gray-800',
    type: 'image',
    price: 290,
    tags: ['4K', 'samurai', 'warrior', 'historical'],
    resolution: '576 × 1024 (9:16)',
    format: 'JPEG / PNG',
    fileSize: '~8MB',
    prompts: [
      'Lone samurai silhouette standing on a misty mountain ridge at sunrise, katana drawn, epic cinematic shot',
      'Two samurai duel in a bamboo forest, dramatic action, motion blur, cherry blossoms falling',
      'Samurai meditating in front of a Shinto shrine, full armor, incense smoke rising, spiritual atmosphere',
      'Samurai warrior on horseback crossing a river in autumn, red maple forest, majestic and powerful',
      'Close-up of samurai armor details, lacquered black and red, intricate craftsmanship, dramatic lighting',
      'Ronin samurai walking through snow-covered village at night, lanterns casting warm glow',
      'Samurai tea ceremony scene, seated warrior removing helmet, peaceful interior, paper screens',
      'Battle-worn samurai standing victorious on a foggy battlefield, dramatic stormy sky',
    ],
    mockImages: [
      'https://images.unsplash.com/photo-1542051841857-5f90071e7989?w=800&q=80',
      'https://images.unsplash.com/photo-1478436127897-769e1b3f0f36?w=800&q=80',
      'https://images.unsplash.com/photo-1508184964240-ee96bb9677a7?w=800&q=80',
    ],
    titleTemplates: [
      'The Last Ronin',
      'Dawn Duel',
      'Warrior\'s Meditation',
      'Autumn Campaign',
      'Armor of Honor',
      'Snowy Vigil',
    ],
  },
  {
    name: 'Fuji',
    nameJa: '富士',
    kanji: '富',
    gradient: 'from-blue-900 to-indigo-800',
    type: 'image',
    price: 190,
    tags: ['4K', 'fuji', 'mountain', 'landscape'],
    resolution: '576 × 1024 (9:16)',
    format: 'JPEG / PNG',
    fileSize: '~8MB',
    prompts: [
      'Mount Fuji at golden hour, perfect reflection in Lake Kawaguchi, cherry blossoms in foreground, iconic Japan',
      'Mount Fuji in winter, snow-capped peak above clouds, dramatic blue sky, traditional red bridge in foreground',
      'Aerial view of Mount Fuji surrounded by autumn foliage, misty clouds at the base, breathtaking scale',
      'Mount Fuji at night, Milky Way galaxy visible above the peak, star trails, long exposure photography',
      'Traditional Japanese pagoda with Mount Fuji in background, cherry blossoms, perfect postcard composition',
      'Mount Fuji seen through torii gates at Fuji Sengen shrine, misty morning, spiritual atmosphere',
      'Sunrise over Mount Fuji from high altitude, sea of clouds below, orange and purple sky',
      'Mount Fuji in rain, moody atmosphere, dark clouds, old wooden fishermen boats on lake',
    ],
    mockImages: [
      'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800&q=80',
      'https://images.unsplash.com/photo-1508184964240-ee96bb9677a7?w=800&q=80',
      'https://images.unsplash.com/photo-1522383225653-ed111181a951?w=800&q=80',
    ],
    titleTemplates: [
      'Fuji at Golden Hour',
      'Sacred Peak in Winter',
      'Above the Clouds',
      'Fuji Star Trails',
      'Pagoda and Mountain',
      'Fuji at Dawn',
    ],
  },
  {
    name: 'Ukiyo-e',
    nameJa: '浮世絵',
    kanji: '浮',
    gradient: 'from-teal-900 to-emerald-800',
    type: 'image',
    price: 290,
    tags: ['4K', 'ukiyo-e', 'art', 'woodblock'],
    resolution: '576 × 1024 (9:16)',
    format: 'JPEG / PNG',
    fileSize: '~8MB',
    prompts: [
      'Great Wave off Kanagawa in hyper-realistic style, dramatic ocean, Mount Fuji in background, Hokusai inspired',
      'Traditional ukiyo-e style Japanese painting of geisha in blooming garden, vivid colors, flat graphic style',
      'Ukiyo-e style dragon emerging from stormy sea, waves crashing, bold lines and colors, Hiroshige inspired',
      'Japanese woodblock print aesthetic, samurai in bamboo forest, dramatic composition, indigo and vermilion',
      'Traditional Japanese print of carp swimming in pond with lotus flowers, koi fish, zen aesthetic',
      'Ukiyo-e style Mount Fuji with seven travelers on mountain path, stylized clouds, classic composition',
      'Japanese woodblock print of autumn deer in maple forest, warm russet and gold tones, elegant',
      'Traditional ukiyo-e crane flying over pine trees and ocean, sunrise, gold and red palette',
    ],
    mockImages: [
      'https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=800&q=80',
      'https://images.unsplash.com/photo-1522383225653-ed111181a951?w=800&q=80',
      'https://images.unsplash.com/photo-1478436127897-769e1b3f0f36?w=800&q=80',
    ],
    titleTemplates: [
      'The Great Wave',
      'Geisha in Spring Garden',
      'Dragon and Storm',
      'Bamboo Forest Print',
      'Koi Pond Harmony',
      'Cranes at Sunrise',
    ],
  },
  {
    name: 'Night',
    nameJa: '夜景',
    kanji: '夜',
    gradient: 'from-violet-950 to-purple-900',
    type: 'image',
    price: 190,
    tags: ['4K', 'night', 'neon', 'atmospheric'],
    resolution: '576 × 1024 (9:16)',
    format: 'JPEG / PNG',
    fileSize: '~8MB',
    prompts: [
      'Tokyo alleyway at night, izakaya lanterns glowing warm orange, rain reflections on wet cobblestones, bokeh lights, no legible text',
      'Osaka river at night, colorful light reflections rippling in the water, crowded bridge silhouettes, no readable signs',
      'Tokyo rooftop view at night, vast cityscape of bokeh lights stretching to horizon, Tokyo Skytree glowing, no text',
      'Traditional Japanese inn at night, paper lanterns casting warm orange glow, koi pond perfectly reflecting starlight',
      'Shinjuku district at midnight seen from above, sea of colorful bokeh lights, moody atmospheric cityscape, no text',
      'Kyoto temple lantern festival at night, hundreds of glowing paper lanterns floating, zen garden, magical atmosphere',
      'Japanese summer festival at night, food stalls with warm golden light, silhouetted crowd in yukata, no signs',
      'Japanese bullet train platform at night, blue-white platform lighting, sleek modern architecture, motion blur',
    ],
    mockImages: [
      'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800&q=80',
      'https://images.unsplash.com/photo-1542051841857-5f90071e7989?w=800&q=80',
      'https://images.unsplash.com/photo-1508184964240-ee96bb9677a7?w=800&q=80',
    ],
    titleTemplates: [
      'Tokyo Alley at Midnight',
      'Osaka Neon River',
      'City of a Million Lights',
      'Lantern Inn Night',
      'Shinjuku Midnight',
      'Festival of Lanterns',
    ],
  },
  {
    name: 'Shibuya',
    nameJa: '渋谷',
    kanji: '渋',
    gradient: 'from-pink-900 to-rose-800',
    type: 'image',
    price: 190,
    tags: ['4K', 'shibuya', 'modern', 'tokyo'],
    resolution: '576 × 1024 (9:16)',
    format: 'JPEG / PNG',
    fileSize: '~8MB',
    prompts: [
      'Shibuya crossing at night, hundreds of pedestrians crossing, neon signs reflecting on wet pavement, cinematic aerial view, no readable text',
      'Modern Tokyo Shibuya district, glass skyscrapers and neon lights, busy intersection at dusk, vibrant energy',
      'Harajuku street fashion scene, colorful pedestrians on Takeshita Street, modern Japan youth culture, no readable signs',
      'Shibuya sky view from rooftop, golden hour cityscape, Tokyo tower in distance, moody atmospheric light',
      'Modern Shinjuku at twilight, towering skyscrapers with glowing windows, busy street below, cinematic composition',
      'Akihabara electric town at night, glowing LED signs and screens, futuristic urban landscape, no legible text',
      'Odaiba waterfront at night, Rainbow Bridge illuminated, reflections on Tokyo Bay, modern cityscape',
      'Roppongi Hills at night, Mori Tower glowing, art illumination, dramatic urban skyline',
    ],
    mockImages: [
      'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800&q=80',
      'https://images.unsplash.com/photo-1542051841857-5f90071e7989?w=800&q=80',
      'https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=800&q=80',
    ],
    titleTemplates: [
      'Shibuya Crossing Night',
      'Neon Tokyo',
      'Harajuku Street Style',
      'Shibuya Sky View',
      'Shinjuku at Twilight',
      'Akihabara Glow',
    ],
  },
  {
    name: 'Shrine',
    nameJa: '神社',
    kanji: '神',
    gradient: 'from-orange-900 to-red-800',
    type: 'image',
    price: 190,
    tags: ['4K', 'shrine', 'spiritual', 'traditional'],
    resolution: '576 × 1024 (9:16)',
    format: 'JPEG / PNG',
    fileSize: '~8MB',
    prompts: [
      'Ancient Japanese Shinto shrine in misty forest, stone torii gate covered in moss, lanterns lighting the path, sacred atmosphere',
      'Traditional Japanese shrine festival, colorful mikoshi portable shrine, crowd in summer yukata, festive atmosphere',
      'Meiji Jingu shrine in Tokyo, grand wooden torii gate, forested path, peaceful and serene, no text',
      'Japanese shrine at cherry blossom season, pink petals falling around red torii gates, spiritual beauty',
      'Itsukushima floating torii gate at high tide, Mount Misen in background, golden sunset, iconic Japan',
      'Mountain shrine in autumn, red maple leaves surrounding ancient stone steps, misty valley below',
      'Lantern lit shrine pathway at dusk, hundreds of stone lanterns glowing amber, cedar forest corridor',
      'Shrine hand washing purification fountain at dawn, stone basin, bamboo ladles, morning mist',
    ],
    mockImages: [
      'https://images.unsplash.com/photo-1478436127897-769e1b3f0f36?w=800&q=80',
      'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=800&q=80',
      'https://images.unsplash.com/photo-1522383225653-ed111181a951?w=800&q=80',
    ],
    titleTemplates: [
      'Sacred Forest Gate',
      'Festival of the Gods',
      'Meiji Shrine Morning',
      'Blossom Shrine',
      'Floating Torii at Sunset',
      'Autumn Mountain Shrine',
    ],
  },
  {
    name: 'Nature',
    nameJa: '自然',
    kanji: '然',
    gradient: 'from-green-900 to-teal-800',
    type: 'image',
    price: 190,
    tags: ['4K', 'nature', 'landscape', 'japan'],
    resolution: '576 × 1024 (9:16)',
    format: 'JPEG / PNG',
    fileSize: '~8MB',
    prompts: [
      'Japanese onsen hot spring surrounded by autumn forest, steam rising in morning light, wooden bath house, serene mountain valley',
      'Hakone open-air museum with Mount Fuji backdrop, green lawns and modern sculpture, clear blue sky',
      'Nikko national park waterfall in summer, lush green forest, ancient stone bridge, magical atmosphere',
      'Japanese countryside rice paddy fields in summer, terraced hillside, rural village, golden afternoon light',
      'Okinawa coral reef beach, crystal clear turquoise water, white sand, tropical paradise',
      'Hokkaido lavender fields in summer, rolling purple hills, blue sky, wide open landscape',
      'Japanese maple garden in peak autumn color, vivid red and orange canopy over stone path, zen garden',
      'Snow monkey bathing in hot spring, Japanese macaques in winter steam, Nagano mountain backdrop',
    ],
    mockImages: [
      'https://images.unsplash.com/photo-1508184964240-ee96bb9677a7?w=800&q=80',
      'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800&q=80',
      'https://images.unsplash.com/photo-1522383225653-ed111181a951?w=800&q=80',
    ],
    titleTemplates: [
      'Mountain Onsen Dawn',
      'Hakone Vista',
      'Nikko Forest Falls',
      'Golden Rice Fields',
      'Okinawa Paradise',
      'Hokkaido Lavender',
    ],
  },
]

module.exports = categories
