// 日本テーマのカテゴリーとプロンプト集
// モックモード時はmockImagesからランダムに画像を選ぶ
// 本番モード時はpromptsをAIに渡して画像を生成する

const categories = [
  {
    name: 'Edo',
    nameJa: '江戸',
    kanji: '江',
    gradient: 'from-amber-950 to-yellow-900',
    type: 'image',
    price: 190,
    tags: ['4K', 'historical', 'edo', 'japan'],
    resolution: '4096 × 2731 (4K)',
    format: 'JPEG / PNG',
    fileSize: '~30MB',
    prompts: [
      'Edo period Tokyo street scene, merchants and samurai walking, traditional wooden buildings, lanterns glowing at dusk, ukiyo-e style, highly detailed',
      'Edo era Japanese marketplace, vibrant and bustling, kimono-clad figures, wooden stalls selling fish and vegetables, dramatic lighting',
      'Samurai warrior in full armor standing in an Edo period castle courtyard, cherry blossoms falling, cinematic composition',
      'Traditional Japanese bathhouse in Edo period, steam rising, wooden architecture, atmospheric mist, warm golden light',
      'Edo period canal scene with merchant boats, weeping willows, stone lanterns reflecting in calm water, twilight',
      'Ancient Edo castle gates at sunrise, mist over the moat, pine trees, majestic and serene atmosphere',
      'Traditional Japanese teahouse in Edo era garden, tatami floors visible, bamboo fence, soft morning light',
      'Edo period sumo wrestling match, crowd watching in traditional wooden arena, dramatic action pose',
    ],
    mockImages: [
      'https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=800&q=80',
      'https://images.unsplash.com/photo-1478436127897-769e1b3f0f36?w=800&q=80',
      'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=800&q=80',
    ],
    titleTemplates: [
      'Edo Market at Dusk',
      'Samurai\'s Path',
      'Castle Gate at Dawn',
      'Old Tokyo Canal',
      'Merchant Quarter',
      'Edo Teahouse Garden',
    ],
  },
  {
    name: 'Kyoto',
    nameJa: '京都',
    kanji: '京',
    gradient: 'from-red-950 to-pink-900',
    type: 'image',
    price: 190,
    tags: ['4K', 'kyoto', 'temple', 'traditional'],
    resolution: '4096 × 2731 (4K)',
    format: 'JPEG / PNG',
    fileSize: '~28MB',
    prompts: [
      'Fushimi Inari shrine at dawn, thousands of vermilion torii gates, morning mist, no people, ethereal atmosphere',
      'Arashiyama bamboo grove in Kyoto, towering green stalks, dappled sunlight, peaceful and meditative',
      'Kinkaku-ji golden pavilion reflected in mirror-still pond, autumn maple trees, warm afternoon light',
      'Gion district Kyoto at night, traditional machiya townhouses, paper lanterns, cobblestone streets glistening',
      'Geisha in elaborate kimono walking through Kyoto autumn garden, maple leaves falling, cinematic',
      'Philosopher\'s Path Kyoto in spring, canal lined with cherry blossoms in full bloom, stone path',
      'Nishiki Market Kyoto, colorful food stalls, traditional Japanese ingredients, vibrant and bustling',
      'Kyoto zen temple raked gravel garden, moss and stones, minimalist composition, morning light',
    ],
    mockImages: [
      'https://images.unsplash.com/photo-1478436127897-769e1b3f0f36?w=800&q=80',
      'https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=800&q=80',
      'https://images.unsplash.com/photo-1522383225653-ed111181a951?w=800&q=80',
    ],
    titleTemplates: [
      'Fushimi Inari at Dawn',
      'Bamboo Grove Silence',
      'Golden Temple Reflection',
      'Gion Night Walk',
      'Philosopher\'s Path Spring',
      'Zen Garden Morning',
    ],
  },
  {
    name: 'Samurai',
    nameJa: '侍',
    kanji: '侍',
    gradient: 'from-slate-900 to-gray-800',
    type: 'image',
    price: 290,
    tags: ['4K', 'samurai', 'warrior', 'historical'],
    resolution: '4096 × 2731 (4K)',
    format: 'JPEG / PNG',
    fileSize: '~35MB',
    prompts: [
      'Lone samurai silhouette standing on a misty mountain ridge at sunrise, katana drawn, epic cinematic shot',
      'Two samurai duel in a bamboo forest, dramatic action, motion blur, cherry blossoms falling',
      'Samurai meditating in front of a Shinto shrine, full armor, incense smoke rising, spiritual atmosphere',
      'Samurai warrior on horseback crossing a river in autumn, red maple forest, majestic and powerful',
      'Close-up of samurai armor details, lacquered black and red, intricate craftsmanship, dramatic lighting',
      'Ronin samurai walking through snow-covered village at night, lanterns casting warm glow',
      'Samurai tea ceremony scene, seated warrior removing helmet, peaceful interior, paper screens',
      'Battle-worn samurai standing victorious on a foggy battlefield, dramatic stormy sky',
    ],
    mockImages: [
      'https://images.unsplash.com/photo-1542051841857-5f90071e7989?w=800&q=80',
      'https://images.unsplash.com/photo-1478436127897-769e1b3f0f36?w=800&q=80',
      'https://images.unsplash.com/photo-1508184964240-ee96bb9677a7?w=800&q=80',
    ],
    titleTemplates: [
      'The Last Ronin',
      'Dawn Duel',
      'Warrior\'s Meditation',
      'Autumn Campaign',
      'Armor of Honor',
      'Snowy Vigil',
    ],
  },
  {
    name: 'Fuji',
    nameJa: '富士',
    kanji: '富',
    gradient: 'from-blue-900 to-indigo-800',
    type: 'image',
    price: 190,
    tags: ['4K', 'fuji', 'mountain', 'landscape'],
    resolution: '4096 × 2731 (4K)',
    format: 'JPEG / PNG',
    fileSize: '~32MB',
    prompts: [
      'Mount Fuji at golden hour, perfect reflection in Lake Kawaguchi, cherry blossoms in foreground, iconic Japan',
      'Mount Fuji in winter, snow-capped peak above clouds, dramatic blue sky, traditional red bridge in foreground',
      'Aerial view of Mount Fuji surrounded by autumn foliage, misty clouds at the base, breathtaking scale',
      'Mount Fuji at night, Milky Way galaxy visible above the peak, star trails, long exposure photography',
      'Traditional Japanese pagoda with Mount Fuji in background, cherry blossoms, perfect postcard composition',
      'Mount Fuji seen through torii gates at Fuji Sengen shrine, misty morning, spiritual atmosphere',
      'Sunrise over Mount Fuji from high altitude, sea of clouds below, orange and purple sky',
      'Mount Fuji in rain, moody atmosphere, dark clouds, old wooden fishermen boats on lake',
    ],
    mockImages: [
      'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800&q=80',
      'https://images.unsplash.com/photo-1508184964240-ee96bb9677a7?w=800&q=80',
      'https://images.unsplash.com/photo-1522383225653-ed111181a951?w=800&q=80',
    ],
    titleTemplates: [
      'Fuji at Golden Hour',
      'Sacred Peak in Winter',
      'Above the Clouds',
      'Fuji Star Trails',
      'Pagoda and Mountain',
      'Fuji at Dawn',
    ],
  },
  {
    name: 'Ukiyo-e',
    nameJa: '浮世絵',
    kanji: '浮',
    gradient: 'from-teal-900 to-emerald-800',
    type: 'image',
    price: 290,
    tags: ['4K', 'ukiyo-e', 'art', 'woodblock'],
    resolution: '4096 × 2731 (4K)',
    format: 'JPEG / PNG',
    fileSize: '~25MB',
    prompts: [
      'Great Wave off Kanagawa in hyper-realistic style, dramatic ocean, Mount Fuji in background, Hokusai inspired',
      'Traditional ukiyo-e style Japanese painting of geisha in blooming garden, vivid colors, flat graphic style',
      'Ukiyo-e style dragon emerging from stormy sea, waves crashing, bold lines and colors, Hiroshige inspired',
      'Japanese woodblock print aesthetic, samurai in bamboo forest, dramatic composition, indigo and vermilion',
      'Traditional Japanese print of carp swimming in pond with lotus flowers, koi fish, zen aesthetic',
      'Ukiyo-e style Mount Fuji with seven travelers on mountain path, stylized clouds, classic composition',
      'Japanese woodblock print of autumn deer in maple forest, warm russet and gold tones, elegant',
      'Traditional ukiyo-e crane flying over pine trees and ocean, sunrise, gold and red palette',
    ],
    mockImages: [
      'https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=800&q=80',
      'https://images.unsplash.com/photo-1522383225653-ed111181a951?w=800&q=80',
      'https://images.unsplash.com/photo-1478436127897-769e1b3f0f36?w=800&q=80',
    ],
    titleTemplates: [
      'The Great Wave',
      'Geisha in Spring Garden',
      'Dragon and Storm',
      'Bamboo Forest Print',
      'Koi Pond Harmony',
      'Cranes at Sunrise',
    ],
  },
  {
    name: 'Night',
    nameJa: '夜景',
    kanji: '夜',
    gradient: 'from-violet-950 to-purple-900',
    type: 'image',
    price: 190,
    tags: ['4K', 'night', 'neon', 'atmospheric'],
    resolution: '4096 × 2731 (4K)',
    format: 'JPEG / PNG',
    fileSize: '~28MB',
    prompts: [
      'Tokyo alleyway at night, neon signs in Japanese, izakaya lanterns, rain reflections on cobblestones, cinematic',
      'Osaka Dotonbori at night, neon advertisements reflecting in river, crowded bridge, vibrant energy',
      'Tokyo rooftop view at night, vast cityscape of lights stretching to horizon, Skytree glowing',
      'Traditional Japanese inn at night, paper lanterns glowing orange, koi pond reflecting stars',
      'Shinjuku street at midnight, neon lights, vending machines, urban Japan nightlife, moody atmosphere',
      'Kyoto temple at night with lantern festival, hundreds of glowing lanterns, zen garden, magical',
      'Night market in Japan, steam from food stalls, golden light, happy crowd, festive atmosphere',
      'Japanese bullet train station at night, platforms lit blue and white, sleek modern architecture',
    ],
    mockImages: [
      'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800&q=80',
      'https://images.unsplash.com/photo-1542051841857-5f90071e7989?w=800&q=80',
      'https://images.unsplash.com/photo-1508184964240-ee96bb9677a7?w=800&q=80',
    ],
    titleTemplates: [
      'Tokyo Alley at Midnight',
      'Osaka Neon River',
      'City of a Million Lights',
      'Lantern Inn Night',
      'Shinjuku Midnight',
      'Festival of Lanterns',
    ],
  },
]

module.exports = categories
